apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4
  labels:   # Added labels for consistency
    app: service4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service4
  template:
    metadata:
      labels:
        app: service4
    spec:
      containers:
        - name: service4
          image: sahilsaini22/microservicedemo:service4
          ports:
            - containerPort: 8500
          livenessProbe:  # Ensure the container is healthy
            httpGet:
              path: /
              port: 8500
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:   # Added a readiness probe
            httpGet:
              path: /
              port: 8500
            initialDelaySeconds: 2
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: service4
  labels:   # Added labels to match the deployment
    app: service4
spec:
  selector:
    app: service4
  ports:
    - protocol: TCP
      port: 80       # This is exposed by the service
      targetPort: 8500  # This must match the container port!
  type: ClusterIP
