apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
  labels:
    app: service3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: service3:latest  # Make sure to load this image into KIND
        imagePullPolicy: Never     # Use local image
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  type: NodePort
  selector:
    app: service3
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30002  # Expose on port 30003 (change if needed)
