apiVersion: apps/v1
kind: Deployment
metadata:
  name: service5
  labels:
    app: service5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service5
  template:
    metadata:
      labels:
        app: service5
    spec:
      containers:
        - name: service5
          image: sahilsaini22/microservicedemo:service5
          ports:
            - containerPort: 8600

---
apiVersion: v1
kind: Service
metadata:
  name: service5
spec:
  type: ClusterIP  # Change from NodePort to ClusterIP
  selector:
    app: service5
  ports:
    - protocol: TCP
      port: 8600
      targetPort: 8600
