apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
  labels:
    app: service1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: service1:latest # Your local image
        imagePullPolicy: Never     # Use local image
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service1-service
spec:
  selector:
    app: service1
  ports:
  - protocol: TCP
    port: 5000         # Expose the Service on port 3000
    targetPort: 5000   # Route traffic to the container's port
  type: LoadBalancer