apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-deployment
  labels:
    app: service2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: service2:latest # Your local image
        imagePullPolicy: Never     # Use local image
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: service2-service
spec:
  selector:
    app: service2
  ports:
  - protocol: TCP
    port: 7000         # Expose the Service on port 3000
    targetPort: 7000   # Route traffic to the container's port
  type: LoadBalancer